const COUNTRY_FLAGS: Record<string, string> = {
  Argentina: "🇦🇷",
  Brasil: "🇧🇷",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Chile: "🇨🇱",
  Ecuador: "🇪🇨",
  Perú: "🇵🇪",
  Paraguay: "🇵🇾",
  Venezuela: "🇻🇪",
  Bolivia: "🇧🇴",
  México: "🇲🇽",
  "Estados Unidos": "🇺🇸",
  USA: "🇺🇸",
  Canadá: "🇨🇦",
  "Costa Rica": "🇨🇷",
  Panamá: "🇵🇦",
  Honduras: "🇭🇳",
  "El Salvador": "🇸🇻",
  Guatemala: "🇬🇹",
  Cuba: "🇨🇺",
  Haití: "🇭🇹",
  "República Dominicana": "🇩🇴",
  Jamaica: "🇯🇲",
  "Trinidad y Tobago": "🇹🇹",
  España: "🇪🇸",
  Francia: "🇫🇷",
  Alemania: "🇩🇪",
  Italia: "🇮🇹",
  Inglaterra: "🇬🇧",
  Portugal: "🇵🇹",
  "Países Bajos": "🇳🇱",
  Holanda: "🇳🇱",
  Bélgica: "🇧🇪",
  Croacia: "🇭🇷",
  Serbia: "🇷🇸",
  Suiza: "🇨🇭",
  Dinamarca: "🇩🇰",
  Suecia: "🇸🇪",
  Noruega: "🇳🇴",
  Polonia: "🇵🇱",
  Ucrania: "🇺🇦",
  Rusia: "🇷🇺",
  Turquía: "🇹🇷",
  Grecia: "🇬🇷",
  Escocia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Gales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Irlanda: "🇮🇪",
  "Irlanda del Norte": "🇬🇧",
  Austria: "🇦🇹",
  Hungría: "🇭🇺",
  "República Checa": "🇨🇿",
  Eslovaquia: "🇸🇰",
  Eslovenia: "🇸🇮",
  Rumania: "🇷🇴",
  Bulgaria: "🇧🇬",
  Finlandia: "🇫🇮",
  Islandia: "🇮🇸",
  Albania: "🇦🇱",
  "Macedonia del Norte": "🇲🇰",
  Montenegro: "🇲🇪",
  Bosnia: "🇧🇦",
  Georgia: "🇬🇪",
  Armenia: "🇦🇲",
  Israel: "🇮🇱",
  Nigeria: "🇳🇬",
  Ghana: "🇬🇭",
  Senegal: "🇸🇳",
  Camerún: "🇨🇲",
  "Costa de Marfil": "🇨🇮",
  Egipto: "🇪🇬",
  Marruecos: "🇲🇦",
  Argelia: "🇩🇿",
  Túnez: "🇹🇳",
  Sudáfrica: "🇿🇦",
  Congo: "🇨🇩",
  Zambia: "🇿🇲",
  Malí: "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "Cabo Verde": "🇨🇻",
  Guinea: "🇬🇳",
  "Guinea Ecuatorial": "🇬🇶",
  "Guinea-Bisáu": "🇬🇼",
  "Sierra Leona": "🇸🇱",
  Liberia: "🇱🇷",
  Togo: "🇹🇬",
  Benín: "🇧🇯",
  Níger: "🇳🇪",
  Chad: "🇹🇩",
  Sudán: "🇸🇩",
  Etiopía: "🇪🇹",
  Kenia: "🇰🇪",
  Uganda: "🇺🇬",
  Tanzania: "🇹🇿",
  Mozambique: "🇲🇿",
  Angola: "🇦🇴",
  Namibia: "🇳🇦",
  Botsuana: "🇧🇼",
  Zimbabue: "🇿🇼",
  Madagascar: "🇲🇬",
  Mauricio: "🇲🇺",
  Japón: "🇯🇵",
  "Corea del Sur": "🇰🇷",
  "Corea del Norte": "🇰🇵",
  China: "🇨🇳",
  "Arabia Saudita": "🇸🇦",
  Irán: "🇮🇷",
  Iraq: "🇮🇶",
  Qatar: "🇶🇦",
  "Emiratos Árabes Unidos": "🇦🇪",
  Omán: "🇴🇲",
  Baréin: "🇧🇭",
  Kuwait: "🇰🇼",
  Líbano: "🇱🇧",
  Siria: "🇸🇾",
  Jordania: "🇯🇴",
  Yemen: "🇾🇪",
  Uzbekistán: "🇺🇿",
  Kazajistán: "🇰🇿",
  Kirguistán: "🇰🇬",
  Tayikistán: "🇹🇯",
  Turkmenistán: "🇹🇲",
  India: "🇮🇳",
  Pakistán: "🇵🇰",
  Bangladés: "🇧🇩",
  Tailandia: "🇹🇭",
  Vietnam: "🇻🇳",
  Camboya: "🇰🇭",
  Laos: "🇱🇦",
  Myanmar: "🇲🇲",
  Malasia: "🇲🇾",
  Singapur: "🇸🇬",
  Indonesia: "🇮🇩",
  Filipinas: "🇵🇭",
  "Timor Oriental": "🇹🇱",
  Australia: "🇦🇺",
  "Nueva Zelanda": "🇳🇿",
  Fiyi: "🇫🇯",
  Tahití: "🇵🇫",
  "Nueva Caledonia": "🇳🇨",
  "Papúa Nueva Guinea": "🇵🇬",
  "Islas Salomón": "🇸🇧",
  Samoa: "🇼🇸",
  Tonga: "🇹🇴",
  Vanuatu: "🇻🇺",
  "Estados Federados de Micronesia": "🇫🇲",
  Palaos: "🇵🇼",
  "Islas Marshall": "🇲🇭",
  Kiribati: "🇰🇮",
  Nauru: "🇳🇷",
  Tuvalu: "🇹🇻",
};

export function getTeamFlag(name: string): string {
  const clean = name?.trim() || "";
  if (COUNTRY_FLAGS[clean]) return COUNTRY_FLAGS[clean];
  for (const [key, flag] of Object.entries(COUNTRY_FLAGS)) {
    if (clean.toLowerCase().includes(key.toLowerCase())) return flag;
  }
  return "";
}
