const COUNTRY_CODES: Record<string, string> = {
  Argentina: "ar",
  Brasil: "br",
  Uruguay: "uy",
  Colombia: "co",
  Chile: "cl",
  Ecuador: "ec",
  Perú: "pe",
  Paraguay: "py",
  Venezuela: "ve",
  Bolivia: "bo",
  México: "mx",
  "Estados Unidos": "us",
  USA: "us",
  Canadá: "ca",
  "Costa Rica": "cr",
  Panamá: "pa",
  Honduras: "hn",
  "El Salvador": "sv",
  Guatemala: "gt",
  Cuba: "cu",
  Haití: "ht",
  "República Dominicana": "do",
  Jamaica: "jm",
  "Trinidad y Tobago": "tt",
  España: "es",
  Francia: "fr",
  Alemania: "de",
  Italia: "it",
  Inglaterra: "gb-eng",
  Portugal: "pt",
  "Países Bajos": "nl",
  Holanda: "nl",
  Bélgica: "be",
  Croacia: "hr",
  Serbia: "rs",
  Suiza: "ch",
  Dinamarca: "dk",
  Suecia: "se",
  Noruega: "no",
  Polonia: "pl",
  Ucrania: "ua",
  Rusia: "ru",
  Turquía: "tr",
  Grecia: "gr",
  Escocia: "gb-sct",
  Gales: "gb-wls",
  Irlanda: "ie",
  "Irlanda del Norte": "gb-nir",
  Austria: "at",
  Hungría: "hu",
  "República Checa": "cz",
  Eslovaquia: "sk",
  Eslovenia: "si",
  Rumania: "ro",
  Bulgaria: "bg",
  Finlandia: "fi",
  Islandia: "is",
  Albania: "al",
  "Macedonia del Norte": "mk",
  Montenegro: "me",
  Bosnia: "ba",
  Georgia: "ge",
  Armenia: "am",
  Israel: "il",
  Nigeria: "ng",
  Ghana: "gh",
  Senegal: "sn",
  Camerún: "cm",
  "Costa de Marfil": "ci",
  Egipto: "eg",
  Marruecos: "ma",
  Argelia: "dz",
  Túnez: "tn",
  Sudáfrica: "za",
  Congo: "cd",
  Zambia: "zm",
  Malí: "ml",
  "Burkina Faso": "bf",
  "Cabo Verde": "cv",
  Guinea: "gn",
  "Guinea Ecuatorial": "gq",
  "Guinea-Bisáu": "gw",
  "Sierra Leona": "sl",
  Liberia: "lr",
  Togo: "tg",
  Benín: "bj",
  Níger: "ne",
  Chad: "td",
  Sudán: "sd",
  Etiopía: "et",
  Kenia: "ke",
  Uganda: "ug",
  Tanzania: "tz",
  Mozambique: "mz",
  Angola: "ao",
  Namibia: "na",
  Botsuana: "bw",
  Zimbabue: "zw",
  Madagascar: "mg",
  Mauricio: "mu",
  Japón: "jp",
  "Corea del Sur": "kr",
  "Corea del Norte": "kp",
  China: "cn",
  "Arabia Saudita": "sa",
  Irán: "ir",
  Iraq: "iq",
  Qatar: "qa",
  "Emiratos Árabes Unidos": "ae",
  Omán: "om",
  Baréin: "bh",
  Kuwait: "kw",
  Líbano: "lb",
  Siria: "sy",
  Jordania: "jo",
  Yemen: "ye",
  Uzbekistán: "uz",
  Kazajistán: "kz",
  Kirguistán: "kg",
  Tayikistán: "tj",
  Turkmenistán: "tm",
  India: "in",
  Pakistán: "pk",
  Bangladés: "bd",
  Tailandia: "th",
  Vietnam: "vn",
  Camboya: "kh",
  Laos: "la",
  Myanmar: "mm",
  Malasia: "my",
  Singapur: "sg",
  Indonesia: "id",
  Filipinas: "ph",
  "Timor Oriental": "tl",
  Australia: "au",
  "Nueva Zelanda": "nz",
  Fiyi: "fj",
  Tahití: "pf",
  "Nueva Caledonia": "nc",
  "Papúa Nueva Guinea": "pg",
  "Islas Salomón": "sb",
  Samoa: "ws",
  Tonga: "to",
  Vanuatu: "vu",
  "Estados Federados de Micronesia": "fm",
  Palaos: "pw",
  "Islas Marshall": "mh",
  Kiribati: "ki",
  Nauru: "nr",
  Tuvalu: "tv",
};

const FLAG_BASE = "https://flagcdn.com/20x15/";

export function getTeamFlag(name: string): string {
  const clean = name?.trim() || "";
  if (COUNTRY_CODES[clean]) return FLAG_BASE + COUNTRY_CODES[clean] + ".png";
  for (const [key, code] of Object.entries(COUNTRY_CODES)) {
    if (clean.toLowerCase().includes(key.toLowerCase())) return FLAG_BASE + code + ".png";
  }
  return "";
}
